export const rowHeaders = [
  'Muscle Group',
  'Maintenance Volume',
  'Minimum Effective Volume',
  'Maximum Adaptive Volume',
  'Maximum Recoverable Volume',
];

export const rowData = [
  [
    { title: 'Abs', highlight: false, range: { min: 0, max: 0 } },
    { title: '0 sets', highlight: false, range: { min: 0, max: 0 } },
    { title: '0 sets', highlight: false, range: { min: 0, max: 15 } },
    { title: '16 - 20 sets', highlight: false, range: { min: 16, max: 20 } },
    { title: '25 sets', highlight: false, range: { min: 21, max: 50 } },
  ],
  [
    { title: 'Back', highlight: false, range: { min: 0, max: 0 } },
    { title: '8 sets', highlight: false, range: { min: 8, max: 9 } },
    { title: '10 sets', highlight: false, range: { min: 10, max: 13 } },
    { title: '14 - 22 sets', highlight: false, range: { min: 14, max: 22 } },
    { title: '25 sets', highlight: false, range: { min: 23, max: 50 } },
  ],
  [
    { title: 'Biceps', highlight: false, range: { min: 0, max: 0 } },
    { title: '8 sets', highlight: false, range: { min: 8, max: 10 } },
    { title: '10 sets', highlight: false, range: { min: 10, max: 13 } },
    { title: '14 - 20 sets', highlight: false, range: { min: 14, max: 22 } },
    { title: '26 sets', highlight: false, range: { min: 22, max: 50 } },
  ],
  [
    { title: 'Calves', highlight: false, range: { min: 0, max: 0 } },
    { title: '6 sets', highlight: false, range: { min: 6, max: 7 } },
    { title: '8 sets', highlight: false, range: { min: 8, max: 11 } },
    { title: '12 - 16 sets', highlight: false, range: { min: 12, max: 16 } },
    { title: '20 sets', highlight: false, range: { min: 17, max: 50 } },
  ],
  [
    { title: 'Chest', highlight: false, range: { min: 0, max: 0 } },
    { title: '8 sets', highlight: false, range: { min: 8, max: 9 } },
    { title: '10 sets', highlight: false, range: { min: 9, max: 11 } },
    { title: '12 - 20 sets', highlight: false, range: { min: 12, max: 20 } },
    { title: '22 sets', highlight: false, range: { min: 21, max: 50 } },
  ],
  [
    { title: 'Delt - Side', highlight: false, range: { min: 0, max: 0 } },
    { title: '6 sets', highlight: false, range: { min: 6, max: 7 } },
    { title: '8 sets', highlight: false, range: { min: 8, max: 15 } },
    { title: '16 - 22 sets', highlight: false, range: { min: 16, max: 22 } },
    { title: '26 sets', highlight: false, range: { min: 23, max: 50 } },
  ],
  [
    { title: 'Delt - Front', highlight: false, range: { min: 0, max: 0 } },
    { title: '0 sets', highlight: false, range: { min: 0, max: 0 } },
    { title: '0 sets', highlight: false, range: { min: 0, max: 5 } },
    { title: '6 - 8 sets', highlight: false, range: { min: 6, max: 8 } },
    { title: '12 sets', highlight: false, range: { min: 9, max: 50 } },
  ],
  [
    { title: 'Delt - Rear', highlight: false, range: { min: 0, max: 0 } },
    { title: '0 sets', highlight: false, range: { min: 0, max: 0 } },
    { title: '8 sets', highlight: false, range: { min: 8, max: 15 } },
    { title: '16 - 22 sets', highlight: false, range: { min: 16, max: 22 } },
    { title: '26 sets', highlight: false, range: { min: 23, max: 50 } },
  ],
  [
    { title: 'Glutes', highlight: false, range: { min: 0, max: 0 } },
    { title: '0 sets', highlight: false, range: { min: 0, max: 0 } },
    { title: '0 sets', highlight: false, range: { min: 0, max: 3 } },
    { title: '4 - 12 sets', highlight: false, range: { min: 4, max: 12 } },
    { title: '16 sets', highlight: false, range: { min: 13, max: 50 } },
  ],
  [
    { title: 'Hamstring', highlight: false, range: { min: 0, max: 0 } },
    { title: '4 sets', highlight: false, range: { min: 4, max: 5 } },
    { title: '6 sets', highlight: false, range: { min: 6, max: 9 } },
    { title: '10 - 16 sets', highlight: false, range: { min: 10, max: 16 } },
    { title: '20 sets', highlight: false, range: { min: 17, max: 50 } },
  ],
  [
    { title: 'Quads', highlight: false, range: { min: 0, max: 0 } },
    { title: '6 sets', highlight: false, range: { min: 6, max: 7 } },
    { title: '8 sets', highlight: false, range: { min: 8, max: 11 } },
    { title: '12 - 18 sets', highlight: false, range: { min: 12, max: 18 } },
    { title: '20 sets', highlight: false, range: { min: 19, max: 50 } },
  ],
  [
    { title: 'Traps', highlight: false, range: { min: 0, max: 0 } },
    { title: '0 sets', highlight: false, range: { min: 0, max: 0 } },
    { title: '0 sets', highlight: false, range: { min: 0, max: 11 } },
    { title: '12 - 20 sets', highlight: false, range: { min: 12, max: 20 } },
    { title: '26 sets', highlight: false, range: { min: 21, max: 50 } },
  ],
  [
    { title: 'Triceps', highlight: false, range: { min: 0, max: 0 } },
    { title: '4 sets', highlight: false, range: { min: 4, max: 5 } },
    { title: '6 sets', highlight: false, range: { min: 6, max: 9 } },
    { title: '10 - 15 sets', highlight: false, range: { min: 10, max: 15 } },
    { title: '18 sets', highlight: false, range: { min: 16, max: 50 } },
  ],
];
